<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316114831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(50) NOT NULL, type VARCHAR(25) NOT NULL, rarity VARCHAR(5) NOT NULL, attack INT NOT NULL, defense INT NOT NULL, age VARCHAR(15) NOT NULL, ADD user_id INT DEFAULT NULL, ADD url_image TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_161498D3D17F50A6 ON card (uuid)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, username VARCHAR(50) NOT NULL, ADD password VARCHAR(255) NOT NULL, ADD last_pull TYPE VARCHAR(15) DEFAULT NULL, ADD pulls_used_today INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649D17F50A6 ON "user" (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('CREATE INDEX IDX_161498D3A76ED395 ON card (user_id)');
        $this->addSql('CREATE TABLE user_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6C95D41AD17F50A6 ON user_card (uuid)');
        $this->addSql('CREATE INDEX IDX_6C95D41AA76ED395 ON user_card (user_id)');
        $this->addSql('CREATE INDEX IDX_6C95D41A4ACC9A20 ON user_card (card_id)');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41A4ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) NOT DEFERRABLE');
        $this->addSql('CREATE TABLE battle_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_player_won BOOLEAN NOT NULL, user_card_id INT NOT NULL, enemy_card_id INT NOT NULL, ADD user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ED25C428D17F50A6 ON battle_history (uuid)');
        $this->addSql('CREATE INDEX IDX_ED25C42812C1842A ON battle_history (user_card_id)');
        $this->addSql('CREATE INDEX IDX_ED25C428DFF7F4D9 ON battle_history (enemy_card_id)');
        $this->addSql('ALTER TABLE battle_history ADD CONSTRAINT FK_ED25C42812C1842A FOREIGN KEY (user_card_id) REFERENCES card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE battle_history ADD CONSTRAINT FK_ED25C428DFF7F4D9 FOREIGN KEY (enemy_card_id) REFERENCES card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE battle_history ADD CONSTRAINT FK_ED25C428A76ED395 FOREIGN KEY (user_id) REFERENCES card (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_ED25C428A76ED395 ON battle_history (user_id)');
        $this->addSql('CREATE TABLE environment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(50) NOT NULL, description VARCHAR(100) NOT NULL, affected_type VARCHAR(20) NOT NULL, benefit_type VARCHAR(15) NOT NULL, quantity DOUBLE PRECISION DEFAULT NULL, ADD turns INT DEFAULT 0 NOT NULL, ADD is_up_affected_type BOOLEAN DEFAULT NULL PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4626DE22D17F50A6 ON environment (uuid)');
        $this->addSql('ALTER TABLE battle_history DROP CONSTRAINT fk_ed25c428a76ed395');
        $this->addSql('ALTER TABLE battle_history ADD CONSTRAINT FK_ED25C428A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE card');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41AA76ED395');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41A4ACC9A20');
        $this->addSql('DROP TABLE user_card');
        $this->addSql('ALTER TABLE battle_history DROP CONSTRAINT FK_ED25C42812C1842A');
        $this->addSql('ALTER TABLE battle_history DROP CONSTRAINT FK_ED25C428DFF7F4D9');
        $this->addSql('DROP TABLE battle_history');
        $this->addSql('ALTER TABLE battle_history DROP CONSTRAINT FK_ED25C428A76ED395');
        $this->addSql('DROP INDEX IDX_ED25C428A76ED395');
        $this->addSql('DROP TABLE environment');
    }
}
